- name: "Clone dotfiles for {{ user }}"
  become: yes
  become_user: "{{ user }}"
  git:
    repo: git://github.com/patrislav/dotfiles.git
    dest: /home/{{ user }}/dotfiles
    update: no

- name: Install dotfiles for {{ user }}
  become: yes
  become_user: "{{ user }}"
  command:
    cmd: ./install
    chdir: /home/{{ user }}/dotfiles
